name = "spotify-now-playing"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[kv_namespaces]]
binding = "KV"
id = "209f72a38bd44a529d99bbce7c13f8cc"

[triggers]
crons = ["*/30 * * * *"]

[[routes]]
pattern = "nowplaying.eyrin.jp"
custom_domain = true
