name = "spotify-now-playing"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[kv_namespaces]]
binding = "SPOTIFY_NOW_PLAYING_KV"
id = "42b3d8e238164f89966d351af22e5958"

[triggers]
crons = ["*/30 * * * *"]

[[routes]]
pattern = "now-playing.eyrin.jp"
custom_domain = true
